### ISSUE TITLE
New organization?

### ISSUE THREAD

**Issue by Neustradamus** [DoubleBastionAdmin/roundpin#2]
Dear @DoubleBastionAdmin,

It is possible to create a Double Bation GitHub organization?
And move project into?

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by DoubleBastionAdmin** [comment]
We develop all our software on GitList, which is hosted on our server, so as to have total control over what we do. We created our GitHub repositories just to point to the GitList [repositories](https://git.doublebastion.com/). If GitHub hadn't been bought by MS, we would have used it to host and develop our software. Freedom means independence and you aren't really free as long as you host all your software on the machines of a tech giant who can suspend your account at any moment.

**Comment by Neustradamus** [comment]
@DoubleBastionAdmin: Yes I know, like a lot of other projects, mirrors are good, it is free.
It permits to find new devs, etc..
Easy to create the free org and move the repositories into.

**Comment by DoubleBastionAdmin** [comment]
We won't use GitHub for any other purpose than to point to our GitList repositories and to solve issues for users who don't want to use our self-hosted bug tracker.

**Comment by Neustradamus** [comment]
@DoubleBastionAdmin: Time to remove this account?

**Comment by DoubleBastionAdmin** [comment]
@Neustradamus What do you mean ? Are you suggesting that this GitHub account should be removed ?

**Comment by DoubleBastionAdmin** [comment]
@Neustradamus  If yes, then please be aware that we have the exclusive right to decide where we store and develop our software and what accounts we open or close for our company. Since we took the decision to develop our software on our own git platform, a mirror of our repositories on GitHub would be pointless. This GitHub account serves only as a pointer to our repositories and as an alternative bug tracker. Before entrusting your software development operations to a platform owned by one of today's tech giants, that can sift through your activities and suspend your GitHub account at any moment, and before recommending to others to do the same, perhaps you should read certain articles like [this one](https://en.wikipedia.org/wiki/Halloween_documents) and [this one](https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish).

**Comment by Neustradamus** [comment]
@DoubleBastionAdmin: To be perfect, you must to create a free organization and move all repositories into:
- https://github.com/account/organizations/new

You can convert this account in organization but it is not the solution.

**Comment by DoubleBastionAdmin** [comment]
@Neustradamus We have been very clear about our position.  We won't create any organization on GitHub. This discussion is closed.
